### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by podarok**
Let's get merged our efforts

### CODE REVIEW

**Comment by BR0kEN-** [comment]
@podarok, I'd really love what you are doing, guys! Merge is not possible, because I've chosen another vector of development. But I'm watching to your work and take some ideas to this repo.

**Comment by podarok** [comment]
@BR0kEN- can we merheour effort in order to add you to slack #cibox channel and to discuss merges?

**Comment by BR0kEN-** [comment]
@podarok, we could try.

**Comment by podarok** [comment]
@BR0kEN- added you to the group. Check your github entered email for an access

**Comment by BR0kEN-** [comment]
@podarok, no one there.

**Pull request closed without merging**
